version: '3'
services:
  minecraft_mmccoo:
    image: mmccoo
    container_name: mmccoo
    build:
      context: ./
      dockerfile: ./docker/ubuntu/Dockerfile
    volumes: 
      - ./world/db:/home/db
      - data:/var/www
      
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - data:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"

volumes:
  data:
